name: candidosetest
description: Un questionnaire pour évaluer la probabilité d'une présence de candidose

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^3.1.0
  video_player: ^0.10.2+3
  flutter_web_video_player: ^1.0.0+1
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Medium.ttf
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700